name: Test Alert Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  apply:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Echo Commit Message
        run: echo "${{ github.event.head_commit.message }}"
      - name: Echo Commit Message Title
        run: echo "${{ github.event.head_commit.message.split('\n')[0] }}"
      - name: Echo Commit Message Title With git log --format=%B
        run: echo "$(git log --format=%B -n 1)"
