name: Test Alert Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  apply:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Echo Commit Message
        run: echo "${{ github.event.head_commit.message }}"
      - name: Echo Commit Message Title With git log --format=%B
        run: |
          COMMIT_MESSAGE_HEADER=$(git log -1 --pretty=%B | head -n 1)
          echo "${COMMIT_MESSAGE_HEADER}"
      - name: Save Commit Header
        run: |
          echo "COMMIT_MESSAGE_HEADER=$(git log -1 --pretty=%B | head -n 1)" >> $GITHUB_ENV
      - name: Echo Commit Message Title With env  variable
        run: |
          echo "${COMMIT_MESSAGE_HEADER}"
